[package]
name = "worktimers"
version = "0.2.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
tabled = "0.10.0"
clap = {version = "*", features = ["cargo"]}