name: Build Rust Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        architecture: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.architecture }}
          toolchain: stable

      - name: Build Rust binary
        run: cargo build --release --target ${{ matrix.architecture }}

      - name: Rename binary
        run: mv target/${{ matrix.architecture }}/release/worktimers target/${{ matrix.architecture }}/release/worktimers-darwin-${{ matrix.architecture }}

      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.architecture }}/release/worktimers-darwin-${{ matrix.architecture }}
          tag_name: v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}